### ISSUE TITLE
How to run this program on a server or locally?

### ISSUE THREAD

**Issue by chaeheekang** [SebLeich/storage-manager-2.0#13]
I want to run this program on the server or locally, what should I do? 
My server environment is ubuntu 20.04 and node version is v14.21.3. The npm version is 6.14.18.
I installed npm and run `npm start run `and I get the following error.
![image](https://user-images.githubusercontent.com/78184677/231465689-47cb2556-b281-40cb-8b26-3d6fb697050f.png)
I think I'm getting an error related to **crbug**, but I installed google-chrome on my server and I get this error. 
Is there any solution?

**Comment by SebLeich** [comment]
The issue is that the npm command **serve** in the main branch still tries to run all tests before starting the development server. That issue is already removed in the current feature branch I'm working on.
To run the storage manager locally, you can do one of the following things:

If you want to use the npm run start command, then:
- goto package.json file
- adjust the script "start" in the section "scripts": (starting in line 4)
- change the current command "ng test --watch=false && ng serve" to "ng serve"

If you want to do no adjustments, then:
- do not use npm run start but ng serve

To host the application on a web server, then:
- run ng build with an appropriate --configuration and --base-href that fits your needs
- copy the files provided in dist/storage-manager-2.0 to your server
- now you should be enabled to browse the app
